### ISSUE TITLE
mozna wielokrotnie utworzyc konwersacje z tym samym userem

### ISSUE THREAD

**Issue by xPapla** [GammaBulls/IO-Project#27]

**Comment by xPapla** [comment]
jestes user A

jak istnieje w bazie konwersacja A <--> B to ma nie dodawać tylko zwrócić istniejącą.

pamiętać że kolejność A i B może być dowolna, czyli jak user A stworzy konwersacje z B to B tworząc ją z A ma dostać tą samą

**Comment by kjaksik** [comment]
Rozwiązane przez #31
